# Generated by Django 4.2.3 on 2023-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="firstname",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
