# Generated by Django 4.2.3 on 2023-07-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_customer_firstname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="firstname",
        ),
    ]
